### ISSUE TITLE
Wrong path on Windows

### ISSUE THREAD

**Issue by deathaxe** [rafmjr/SyncMergeScheme#3] opened 2020-05-25 16:52 UTC
The plugin fails with

```
reloading settings Packages/User/Preferences.sublime-settings
Exception in thread Thread-65:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\packages/debounce.py", line 18, in call_it
    fun(*args, **kwargs)
  File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\SyncMergeSchemeCommand.py", line 20, in run
    self.sync_color_scheme(st_color_scheme)
  File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\SyncMergeSchemeCommand.py", line 35, in sync_color_scheme
    with open(file_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DeathAxe\\AppData\\Local\\Sublime Merge\\Sublime Merge\\Packages/User\\Commit Message - Merge.sublime-settings'
```

Correct target directory was `C:\Users\<user>\AppData\Sublime Merge\Packages\User`.

Should also detect Sublime Merge and Sublime Text portable setups installed right next to each other.

e.g.:

C:\Apps\Sublime Text\
C:\Apps\Sublime Merge\

That's what ST/SM support by default.

**Comment by rafmjr** [comment] 2020-05-25 18:16
> The plugin fails with
> 
> 
> 
> ```
> 
> reloading settings Packages/User/Preferences.sublime-settings
> 
> Exception in thread Thread-65:
> 
> Traceback (most recent call last):
> 
>   File "./python3.3/threading.py", line 901, in _bootstrap_inner
> 
>   File "./python3.3/threading.py", line 1142, in run
> 
>   File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\packages/debounce.py", line 18, in call_it
> 
>     fun(*args, **kwargs)
> 
>   File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\SyncMergeSchemeCommand.py", line 20, in run
> 
>     self.sync_color_scheme(st_color_scheme)
> 
>   File "C:\Apps\Sublime Text\Data\Installed Packages\Sync Merge Scheme.sublime-package\SyncMergeSchemeCommand.py", line 35, in sync_color_scheme
> 
>     with open(file_path, 'w') as file:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\DeathAxe\\AppData\\Local\\Sublime Merge\\Sublime Merge\\Packages/User\\Commit Message - Merge.sublime-settings'
> 
> ```
> 
> 
> 
> Correct target directory was `C:\Users\<user>\AppData\Sublime Merge\Packages\User`.
> 
> 
> 
> Should also detect Sublime Merge and Sublime Text portable setups installed right next to each other.
> 
> 
> 
> e.g.:
> 
> 
> 
> C:\Apps\Sublime Text\
> 
> C:\Apps\Sublime Merge\
> 
> 
> 
> That's what ST/SM support by default.

Thank you for reporting this issue, I’m planning to allow users to indicate the path where they installed Sublime Merge in the near future, though I would like to make sure the plugin works as intended on Windows.

**Comment by themilkman** [comment] 2020-05-26 07:50
Just as a follow up on linux:

```
Exception in thread Thread-1573:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/home/MY/.config/sublime-text-3/Installed Packages/Sync Merge Scheme.sublime-package/packages/debounce.py", line 18, in call_it
    fun(*args, **kwargs)
  File "/home/MY/.config/sublime-text-3/Installed Packages/Sync Merge Scheme.sublime-package/SyncMergeSchemeCommand.py", line 20, in run
    self.sync_color_scheme(st_color_scheme)
  File "/home/MY/.config/sublime-text-3/Installed Packages/Sync Merge Scheme.sublime-package/SyncMergeSchemeCommand.py", line 35, in sync_color_scheme
    with open(file_path, 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/MY/.local/share/Sublime Merge/Packages/User/Commit Message - Merge.sublime-settings'
```

I am curious to see this working, the idea sounds good to me - thanks in advance for your work!

**Comment by rafmjr** [comment] 2020-05-30 02:33
I just updated the plugin to [**v1.0.3**](https://github.com/rafmjr/SyncMergeScheme/releases/tag/v1.0.3) in order to enable configuration of where your Sublime Merge setting files should exist when updating the scheme:

https://github.com/rafmjr/SyncMergeScheme#configuration

Please let me know if this helps you getting the plugin to work as expected @deathaxe @themilkman, that way I can close this issue.

**Comment by deathaxe** [comment] 2020-05-30 09:56
You need to take the following facts into account.

1. Don't assume `/` is the only path delimiter. Windows uses `\`. Thus `path.join(sublime.cache_path().replace('/Cache', '')` fails on MS Windows.
2. Both ST and SM may be installed on OS (using a user's profile directory to store data) or being configured to run as portable app (_Data_ folder in the application directory).
3. Syncing fails for both SM and ST being used as portable apps, as SM doesn't skim over the Data directory of a portable ST, which drives this plugin useless for such (my) setups unfortunatelly.

**Portable data dirs**

[path]\Sublime Text\Data
[path]\Sublime Merge\Data


**profile data dirs (Windows)**

%appdata%\Sublime Text or %appdata%\Sublime Text 3
%appdata%\Sublime Merge


**profile data dirs (Linux)**

~/.config/sublime-text  or ~/.config/sublime-text-3
~/.config/sublime-merge

**Comment by rafmjr** [comment] 2020-05-30 21:59
@deathaxe thank you for pointing out the issue with the delimiters, I'll fix it the on the next iteration. Did you try specifying the right path for your SM setup through the settings file?

**Comment by deathaxe** [comment] 2020-05-31 08:13
Yes, I did. The settings files are created correctly, then. Unfortunatelly SM shows an error dialog then, because it is unable to find the color scheme. While SM and ST know about each other's executable files when placed next to each other as portable application, they do not know about their data dirs then.

**Comment by rafmjr** [comment] 2020-05-31 15:27
@deathaxe that sounds more like a limitation imposed by both applications for your current setup than a bug on this plugin unfortunately. However I do appreciate your feedback and help fixing the original issue, thank you very much.

**Closed as completed** 2020-05-31 15:46 UTC
Labels: bug

**Comment by themilkman** [comment] 2020-06-02 07:07
Hi @rafmjr ! Sorry for the late response. Now the plugin works for me, thank you very much for this!

I don't know why/if it is related, but nevertheless I find this error in the logs:

```
reloading settings Packages/User/Preferences.sublime-settings
Exception in thread Thread-122:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 1142, in run
  File "/home/mysweethome/.config/sublime-text-3/Installed Packages/Sync Merge Scheme.sublime-package/packages/debounce.py", line 18, in call_it
    fun(*args, **kwargs)
  File "/home/mysweethome/.config/sublime-text-3/Installed Packages/Sync Merge Scheme.sublime-package/SyncMergeSchemeCommand.py", line 20, in run
    st_color_scheme = sublime.load_settings('Preferences.sublime-settings').get('color_scheme')
AttributeError: 'NoneType' object has no attribute 'load_settings'
```

**Comment by rafmjr** [comment] 2020-06-03 04:04
That is interesting... Is this preventing the plugin to update the scheme in Sublime Merge?

Also, if you are still having this issue, I will appreciate if you could create a new issue explaining how to reproduce the error.

Thank you again for reporting and contributing @themilkman, I’m glad the last updated fixed your issue.

**Comment by themilkman** [comment] 2020-06-03 08:13
Sorry for messing this issue up. I actually cannot reproduce it, maybe a constellation with other plugins (e.g. colored comments or semantic highlighter, don't know). Switching color schemas syncs as expected (well many things are confused in ST+SM when doing it resulting in error popups and glitches), thus never mind, sorry for any confusion. In case I notice anything again I'll open a new issue.
Again, THANKS for this, now for the first time I personally really use/like the dark mode of SM :-)
